### ISSUE TITLE
[Docs] Would you be inclined to add an example with Synchronize?

### ISSUE THREAD

**Issue by gcarreno** [mr-highball/ezthreads#11]
Hey @mr-highball,

First I have to admit that I haven't dived into your framework's code to see if there is an example. I'm sorry if I'm asking for something already obvious on the code.

My ask is quite simple: On `README.md`, add a simple example with main thread synchronization denoted by the use of the `TThread.Synchronise()` procedure. That's it!!

Many thanks in advance!

Cheers,
Gus

**Comment by mr-highball** [comment]
@gcarreno thanks for the interest and yes I did have an example in the UI tester, but it was not clear that is where it could be found. I updated the readme with the snippet as well as a screenshot showing this working in an simple UI app. I'm going to close this issue, but if you other questions please feel free to post another issue or a [discussion](https://github.com/mr-highball/ezthreads/discussions) post

**Comment by gcarreno** [comment]
Hey @mr-highball,

Thank you so very much for this, quite honestly, blazing fast turn around!!

I'll use the discussions for any non issue related stuff, thanks for turning that one !!

Cheers,
Gus

**Comment by mr-highball** [comment]
No problem 👌
Happy threading 👍👍

**Comment by gcarreno** [comment]
Hey @mr-highball ,

Thanks, Imma do some play around with this very soon.
Need to implement a multi-download threaded pool with central downloaded bytes accumulator.
Gonna ask some Qs on the discussions.

Your code has been god sent ;D

Cheers,
Gus

**Comment by mr-highball** [comment]
thank you 😊

**Comment by gcarreno** [comment]
Quite welcome :smiley: !!
