### ISSUE TITLE
[question] How to report progress from download thread?

### ISSUE THREAD

**Issue by GitStorageOne** [mr-highball/ezthreads#14]
Hello!

I have main thread with form and progress bar.  
To download some file I call function that create new thread.  
Is it possible to call at any time some function with synchronisation with main thread?
```pascal
procedure Download(Url: string);
var
  DownloadThread: IEZThread;
begin
  DownloadThread := NewEZThread();
  DownloadThread.AddArg('downloadUrl', Url);
  DownloadThread.Setup(BackgroundDownload);
  DownloadThread.Settings.UpdateSynchronizeStopEvents(True);
  DownloadThread.Events.UpdateOnStopCallback(BackgroundDownloadSetupComplete);
  DownloadThread.Start();
end;

procedure BackgroundDownload(const AThread: IEZThread);
begin
  // Here i have download object with progress callback that on each step has some chunk of data.
  // So i have all data to report progress.
  // But how from this thread (while it is running) i can report download progress to main thread?
  // I'm looking for something like AThread.Synchronize( {some function to execute from main thread} );
end;

procedure BackgroundDownloadSetupComplete(const AThread: IEZThread);
begin
  // Here we are in main thread
  // We can get download results from AThread
end;
```

I saw solution with thread pool, but i'm curious is it possible with this approach.

**Comment by mr-highball** [comment]
Hi!
Yes so what you can do is queue the update to the progress control as long as you are in a different thread than the UI main thread. You'll need to either store the progress amount in the thread arguments AND have a reference to it from your former, or just store a global variable that your UI can access (doesn't have to be fancy).
From my multi file download example, this line does just that
https://github.com/mr-highball/ezthreads/blob/52ecd94299180b6df97ee58657b30455b8d4e8ba/demo/pool-multi-file-download/main.pas#L125 

A lot of what you're probably trying to get working can be ripped out of that example too (take as much or as little as you'd  like, it's free 😀)

If that doesn't answer your question drop a bit more code or a link to a gist/project and I'll be glad to help out 👍

**Comment by GitStorageOne** [comment]
> I saw solution with thread pool, but i'm curious is it possible with this approach.

Well, thread pool for simple file downloader is overkill IMO :)
For multi-file download - sure, thread pool is totally fits.

Here is a working example without thread pool (i figured out how to solve my issue).
Probably you can add `Synchronize(CallBack)` method to `IEZThread` as wrapper for this code:
`TThread.Synchronize(TThread.CurrentThread, CallBack);`.

[download-thread.zip](https://github.com/mr-highball/ezthreads/files/6369556/download-thread.zip)
If you have ideas how to make code more simple, would be glad to see.

**Comment by mr-highball** [comment]
I agree, that would be a good addition, thanks!

I've added #15 to track the effort, feel free to comment or request anything related over there 👍

**Comment by GitStorageOne** [comment]
Looks like i have issue with thread termination :(

```pascal
procedure TDownloader.BackgroundDownload(const AThread: IEZThread);
var
  i: Integer;
begin
  // Emulate download 100 chunks
  for i := 1 to 100 do
   begin
    if StopDownload then // <<<<< Exit from thread loop
      exit;
    Sleep(30);
    // In this demo, i = download progress
    DownloadProgress := i;
    // Looking for something like:
    // AThread.Synchronize(UpdateProgressCallBack);
    TThread.Synchronize(TThread.CurrentThread, UpdateProgressCallBack);
   end;
end;

destructor TDownloader.Destroy();
begin
  StopDownload := True;
  if Assigned(CurrentDownloadThread) then
    Await(CurrentDownloadThread); // Freezes here
  inherited Destroy();
end; 
```

[download-thread.zip](https://github.com/mr-highball/ezthreads/files/6371951/download-thread.zip)

**Comment by mr-highball** [comment]
@GitStorageOne interesting, so it appears that the form close triggers destroy, but calling await is not yielding to the background thread like it should. I had a hunch that in a GUI app something with the close event is preventing the main thread from pumping messages to switch, so I changed your destroy to look like this

```pascal
StopDownload := True;
  if Assigned(CurrentDownloadThread) then
    //Await(CurrentDownloadThread);
    while CurrentDownloadThread.State = esStarted do
    begin
      Application.ProcessMessages;
      continue;
    end;   
```

the stop even also got triggered after the form had been destroyed, so it might also be useful to _clear_ this either in the background thread method (right before exiting) or detecting that your form is still assigned in _unit1.DownloadUpdateCompleteCallBack_.

This is just a temporary workaround, I've put in #16 to code around this in Await since it should be able to handle this case

**Comment by mr-highball** [comment]
@GitStorageOne was a pretty easy fix, #16 is merged in, thanks for reporting. While my comment above is still valid, you don't need to worry about changing anything with what you had if you pull the latest master.

also as a note, you don't need
`If Assigned(CurrentDownloadThread) then`
Await  handles the check for nil threads for you

**Comment by GitStorageOne** [comment]
Ok, now working as expected!

**Comment by mr-highball** [comment]
Great :)
